# Generated by Django 4.2.7 on 2023-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
