# Generated by Django 4.2.7 on 2023-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0004_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backphoto',
            field=models.ImageField(upload_to='uploads/background'),
        ),
    ]
