# Generated by Django 4.2.7 on 2023-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0005_alter_profile_avatar_alter_profile_backphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_videos',
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded_videos',
            field=models.ManyToManyField(to='yt.videos'),
        ),
    ]
