# Generated by Django 4.2.7 on 2023-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0006_remove_profile_uploaded_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='uploaders',
            field=models.ManyToManyField(blank=True, related_name='video_uploads', to='yt.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uploaded_videos',
            field=models.ManyToManyField(blank=True, related_name='profile_uploads', to='yt.videos'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
