# Generated by Django 4.2.7 on 2023-11-17 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yt', '0007_videos_uploaders_alter_profile_uploaded_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
